import type { Metadata } from "next";
import { Fascinate_Inline } from "next/font/google";
import "./globals.css";



const comforter = Fascinate_Inline({ subsets: ["latin"],weight:"400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comforter.className}>
    
        {children}
      </body>
    </html>
  );
}
